name: Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "production"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run build
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: prod
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: prod
          path: out
      - name: Deploy to sepiq.uk by FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER_PROD }}
          password: ${{ secrets.FTP_PASS_PROD }}
          local-dir: ./out/
